### ISSUE TITLE
Account Registration - error handling

### ISSUE THREAD

**Issue by kierancott** [develop-me/bagajob#43]
Error: App crashes (code 422) with no error handling

Issue: registering an account with an email that was already in the database returns the below error - no error handling exists for this behaviour

<img width="1440" alt="93353133-923bad00-f809-11ea-9c35-a6a888e1ac4a" src="https://user-images.githubusercontent.com/52701889/93476446-b5da2280-f8f1-11ea-9816-fac6290b487f.png">

Action: provide the user with an error message

**Comment by kierancott** [comment]
# Resolved
Commit https://github.com/develop-me/bagajob/pull/42/commits/71f2d3db06470aa0dec8e0587e336abee79b7e55

**Action:**

- extract error message from state and render below form
- create function that clears errors on form load

**Result:**

Instead of the app crashing due to unprocessable entity, the below error is shown:

<img width="1281" alt="Screenshot 2020-09-19 at 15 28 08" src="https://user-images.githubusercontent.com/52701889/93669597-397c4680-fa8d-11ea-99b6-1df8d0d754c5.png">

**Comment by nosvalds** [comment]
Hey Kieran,

I'm still seeing this testing on my side. I do see the error message briefly on the screen, but then it bombs out again with the unhandled promise rejection:
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/60047271/93790228-ce538100-fc00-11ea-808c-e05f923b0ff0.png">

**Comment by kierancott** [comment]
I've checked again, and I'm struggling to reproduce that behaviour.

It's handling the rejection and rendering the `authResponse` below the form.

<img width="1345" alt="Screenshot 2020-09-21 at 16 55 17" src="https://user-images.githubusercontent.com/52701889/93790897-74b47c00-fc2b-11ea-8096-3197ff2d8af5.png">

**Comment by kierancott** [comment]
## Resolved:

Fixed by commit https://github.com/develop-me/bagajob/pull/42/commits/b68f7d7c0eec210c3aa2d5f9e91c14a6db8006e8 (thanks, Nik!)

**Comment by nosvalds** [comment]
Resolved!
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/60047271/94011153-f4019700-fd74-11ea-8a6d-9245c27f4b77.png">
